### ISSUE TITLE
Game crash on on ae2wtLIB version 1.12 mod version 1.0.34

### ISSUE THREAD

**Issue by mcintosh109** [p455w0rd/AE2WirelessTerminalLibrary#10]
Unknown crash on MC startup (sorry I like pastbin)
Game version 1.12.2
MC loader: MultiMC
Mod list: https://pastebin.com/f8JeSMHz
The log file: https://paste.ee/p/t7ZZx
Crash report: https://paste.ee/p/MaNEr
Game, OS version and Java version
--Minecraft Version: 1.12.2
--Operating System: Windows 10 (amd64) version 10.0
--Java Version: 1.8.0_231, Oracle Corporation
--Java VM Version: Java HotSpot (TM) 64-Bit Server VM (mixed mode), Oracle Corporation
--Memory In Bytes: 4941657768 bytes  / 8107065344 bytes 8GB allocated to MC

if you need more info or TMI tell me TY
allways a plesure to help the mod community

**Comment by p455w0rd** [comment]
update wct...

**Comment by mcintosh109** [comment]
Nope dido
Chrash Report: https://paste.ee/p/qPMsO
Newst log: https://paste.ee/p/o88jE
