### ISSUE TITLE
errors in server console log during startup

### ISSUE THREAD

**Issue by ghost** [p455w0rd/AE2WirelessTerminalLibrary#21]
Tons of errors in server console log during startup
I am attaching the latest.log the errors are from line 267 to line 652
[latest.log](https://github.com/p455w0rd/AE2WirelessTerminalLibrary/files/7407157/latest.log)

Minecraft 1.16.5
Java 8 - 291
Forge 1.16.5-36.2.6
AE2 8.4.3
AE2 wt lib 0.3.2-1.16.5

Parsing error loading recipe ae2wtlib:wireless_universal_terminal/upgrade_pattern
Parsing error loading recipe ae2wtlib:wireless_universal_terminal/ip
Parsing error loading recipe ae2wtlib:wireless_universal_terminal/ci
Parsing error loading recipe ae2wtlib:wireless_universal_terminal/cp
Parsing error loading recipe ae2wtlib:wireless_universal_terminal/upgrade_interface
Parsing error loading recipe ae2wtlib:wireless_universal_terminal/upgrade_crafting

**Comment by Mari023** [comment]
the 1.16 forge version is a different mod from a different person.
you can find it's issue tracker [here](https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/issues)

**Comment by ghost** [comment]
thanks
