### ISSUE TITLE
When using these Wireless Terminals,break the Security Terminal,and use the bounded terminal,the game crashed

### ISSUE THREAD

**Issue by somerui** [p455w0rd/AE2WirelessTerminalLibrary#24]
The Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.1.10-forge-mc1.12.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Techguns Core ([科技枪] techguns-1.12.2-2.0.2.0_pre3.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/23/23 8:32 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at p455w0rd.ae2wtlib.api.container.ContainerWT.hasAccess(ContainerWT.java:386)
	at p455w0rd.wpt.container.ContainerWPT.func_75142_b(ContainerWPT.java:1033)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at p455w0rd.ae2wtlib.api.container.ContainerWT.hasAccess(ContainerWT.java:386)
	at p455w0rd.wpt.container.ContainerWPT.func_75142_b(ContainerWPT.java:1033)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 458
	Entity Name: somerui
	Entity's Exact location: 109.79, 65.00, -34.30
	Entity's Block location: World: (109,65,-35), Chunk: (at 13,4,13 in 6,-3; contains blocks 96,0,-48 to 111,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Vertoak Map V12
	All players: 1 total; [EntityPlayerMP['somerui'/458, l='Vertoak Map V12', x=109.79, y=65.00, z=-34.30]]
	Chunk stats: ServerChunkCache: 737 Drop: 0
	Level seed: -6784736191283369982
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (14,72,184), Chunk: (at 14,4,8 in 0,11; contains blocks 0,0,176 to 15,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 38721046 game time, 30000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4511193280 bytes (4302 MB) / 6937378816 bytes (6616 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version              | Source                                                   | Signature                                |
	|:------ |:------------------------ |:-------------------- |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2               | minecraft.jar                                            | None                                     |
	| LCHIJA | mcp                      | 9.42                 | minecraft.jar                                            | None                                     |
	| LCHIJA | FML                      | 8.0.99.99            | forge-1.12.2-14.23.5.2860-universal.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2860         | forge-1.12.2-14.23.5.2860-universal.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | techguns_core            | 1.12.2-1.0           | minecraft.jar                                            | None                                     |
	| LCHIJA | replaymod                | 1.12.2-2.6.13        | replaymod-1.12.2-2.6.13.jar                              | None                                     |
	| LCHIJA | mad_villagers            | %VERSION%            | [疯狂的村民] Mad Villagers-1.12.2-1.0.1-release.jar           | None                                     |
	| LCHIJA | ctm                      | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                                | None                                     |
	| LCHIJA | crafttweaker             | 4.1.20               | CraftTweaker2-1.12-4.1.20.685.jar                        | None                                     |
	| LCHIJA | jei                      | 4.16.1.1000          | jei_1.12.2-4.16.1.1000.jar                               | None                                     |
	| LCHIJA | chisel                   | MC1.12.2-1.0.2.45    | Chisel-MC1.12.2-1.0.2.45.jar                             | None                                     |
	| LCHIJA | techguns                 | 2.0.2.0              | [科技枪] techguns-1.12.2-2.0.2.0_pre3.2.jar                 | None                                     |
	| LCHIJA | appliedenergistics2      | rv6-stable-7         | appliedenergistics2-rv6-stable-7.jar                     | None                                     |
	| LCHIJA | baubles                  | 1.5.2                | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJA | mantle                   | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                                 | None                                     |
	| LCHIJA | projecte                 | 1.12.2-PE1.4.1       | ProjectE-1.12.2-PE1.4.1.jar                              | None                                     |
	| LCHIJA | p455w0rdslib             | 2.3.161              | p455w0rdslib-1.12.2-2.3.161.jar                          | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | ae2wtlib                 | 1.0.34               | AE2WTLib-1.12.2-1.0.34.jar                               | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | codechickenlib           | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | avaritia                 | 3.3.0                | Avaritia-1.12.2-3.3.0.37-universal.jar                   | None                                     |
	| LCHIJA | wanionlib                | 1.12.2-2.9           | WanionLib-1.12.2-2.9.jar                                 | None                                     |
	| LCHIJA | avaritiaddons            | 1.12.2-1.7           | Avaritiaddons-1.12.2-1.7.jar                             | None                                     |
	| LCHIJA | avaritiarecipemaker      | 1.0.0                | avaritiarecipemaker-1.0.0.jar                            | None                                     |
	| LCHIJA | botania                  | r1.10-364            | Botania r1.10-364.4.jar                                  | None                                     |
	| LCHIJA | gunpowderlib             | 1.12.2-1.1           | GunpowderLib-1.12.2-1.1.jar                              | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | avaritiatweaks           | 1.12.2-1.3           | AvaritiaTweaks-1.12.2-1.3.jar                            | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | supermartijn642configlib | 1.1.6                | supermartijn642configlib-1.1.6-forge-mc1.12.jar          | None                                     |
	| LCHIJA | supermartijn642corelib   | 1.1.10               | supermartijn642corelib-1.1.10-forge-mc1.12.jar           | None                                     |
	| LCHIJA | chunkloaders             | 1.2.3                | chunkloaders-1.2.3-forge-mc1.12.jar                      | None                                     |
	| LCHIJA | ctgui                    | 1.0.0                | CraftTweaker2-1.12-4.1.20.685.jar                        | None                                     |
	| LCHIJA | crafttweakerjei          | 2.0.3                | CraftTweaker2-1.12-4.1.20.685.jar                        | None                                     |
	| LCHIJA | customnpcs               | 1.12                 | CustomNPCs_1.12.2-(05Jul20).jar                          | None                                     |
	| LCHIJA | orelib                   | 3.6.0.1              | OreLib-1.12.2-3.6.0.1.jar                                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                | @VERSION@            | DynamicSurroundings-1.12.2-3.6.3.jar                     | None                                     |
	| LCHIJA | jiucore                  | 1.1.0-20220608013004 | JiuCore-1.12.2-1.1.0-20220608013004.jar                  | None                                     |
	| LCHIJA | email                    | 1.0.3-a1             | Email-1.0.3-a1.jar                                       | None                                     |
	| LCHIJA | equivalentenergistics    | 0.8.4                | EquivalentEnergistics-1.12.2-PE_1.4.1-0.8.4.jar          | None                                     |
	| LCHIJA | eternalsingularity       | 1.12.2-1.0.7         | eternalsingularity-1.12.2-1.0.7.jar                      | None                                     |
	| LCHIJA | extrabotany              | 60                   | ExtraBotany-r1.1-60-beta-hotfix.jar                      | None                                     |
	| LCHIJA | forgelin                 | 1.8.4                | Forgelin-1.8.4.jar                                       | None                                     |
	| LCHIJA | forgemultipartcbe        | 2.6.2.83             | ForgeMultipart-1.12.2-2.6.2.83-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe            | 2.6.2.83             | ForgeMultipart-1.12.2-2.6.2.83-universal.jar             | None                                     |
	| LCHIJA | minecraftmultipartcbe    | 2.6.2.83             | ForgeMultipart-1.12.2-2.6.2.83-universal.jar             | None                                     |
	| LCHIJA | hole_filler_mod          | 1.0                  | hole_filler_mod-1.2.4.1-mc_1.12.2-forge.jar              | None                                     |
	| LCHIJA | journeymap               | 1.12.2-5.7.1         | journeymap-1.12.2-5.7.1.jar                              | None                                     |
	| LCHIJA | lostcities               | 2.0.22               | lostcities-1.12-2.0.22.jar                               | None                                     |
	| LCHIJA | mcdj                     | 1.3                  | MCDJ-1.12.2-2.0_fix.jar                                  | None                                     |
	| LCHIJA | mcwdoors                 | 1.3                  | mcw-doors-1.0.3-mc1.12.2.jar                             | None                                     |
	| LCHIJA | mcwfences                | 1.0.0                | mcw-fences-1.0.0-mc1.12.2.jar                            | None                                     |
	| LCHIJA | mcwfurnitures            | 1.0.1                | mcw-furniture-1.0.1-mc1.12.2beta.jar                     | None                                     |
	| LCHIJA | mcwtrpdoors              | 1.0.2                | mcw-trapdoors-1.0.3-mc1.12.2.jar                         | None                                     |
	| LCHIJA | mcwwindows               | 1.0                  | mcw-windows-1.0.0-mc1.12.2.jar                           | None                                     |
	| LCHIJA | millenaire               | Millénaire 8.1.2     | millenaire-8.1.2.jar                                     | None                                     |
	| LCHIJA | mm_lib                   | 2.3.0                | MMLib-2.3.0.jar                                          | None                                     |
	| LCHIJA | moreavaritia             | 3.5                  | moreavaritia-mc1.12.2-v1.5.jar                           | None                                     |
	| LCHIJA | torcherino               | 7.6                  | torcherino-7.6.jar                                       | None                                     |
	| LCHIJA | mcs                      | 3.0.3-20220610234154 | MultipleCompressedStuffs-1.12.2-3.0.3-20220610234154.jar | None                                     |
	| LCHIJA | nei                      | 2.4.3                | NotEnoughItems-1.12.2-2.4.3.245-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | oreexcavation            | 1.4.150              | OreExcavation-1.4.150.jar                                | None                                     |
	| LCHIJA | portality                | 1.0-SNAPSHOT         | portality-1.12.2-1.2.3-15.jar                            | None                                     |
	| LCHIJA | projectex                | 1.2.0.40             | ProjectEX-1.2.0.40.jar                                   | None                                     |
	| LCHIJA | scp                      | 2.4.2                | SCP Lockdown-1.12.2-2.4.2-release.jar                    | None                                     |
	| LCHIJA | flammpfeil.slashblade    | mc1.12-r33           | SlashBlade-mc1.12-r33.jar                                | None                                     |
	| LCHIJA | slashblade_addon         | 1.6.0                | SJAP-1.6.0.jar                                           | None                                     |
	| LCHIJA | variedcommodities        | 1.12.2               | VariedCommodities_1.12.2-(31Mar23).jar                   | None                                     |
	| LCHIJA | wct                      | 3.12.97              | WirelessCraftingTerminal-1.12.2-3.12.97.jar              | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | wft                      | 1.0.4                | WirelessFluidTerminal-1.12.2-1.0.4.jar                   | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | wit                      | 1.0.2                | WirelessInterfaceTerminal-1.12.2-1.0.2.jar               | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | wpt                      | 1.0.3                | WirelessPatternTerminal-1.12.2-1.0.3.jar                 | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | worldedit                | 6.1.10               | worldedit-forge-mc1.12.2-6.1.10-dist.jar                 | None                                     |

	Loaded coremods (and transformers): 
SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.1.10-forge-mc1.12.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Techguns Core ([科技枪] techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['somerui'/458, l='Vertoak Map V12', x=109.79, y=65.00, z=-34.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 11
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 528.49
	OpenGlRenderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by sreny1** [comment]
in 1.20.1 ae2 removed the security terminal and wireless terminals are linked through access points.
Same thing happens when you break the access point in that version :(
