### ISSUE TITLE
Wireless Universal Terminal client crash

### ISSUE THREAD

**Issue by Doedelsander** [p455w0rd/AE2WirelessTerminalLibrary#3]
Hello,

When shift clicking the Wireless Universal Terminal, my client (and that of my friend) crash. I tried this on a server with my custom modpack. The server did not crash only the clients who tried it.

[crash-2019-09-04_19.30.03-client.txt](https://github.com/p455w0rd/AE2WirelessTerminalLibrary/files/3575807/crash-2019-09-04_19.30.03-client.txt)

**Comment by Vaati88** [comment]
I too had the same issue.
https://paste.dimdev.org/jayiyozori.mccrash

**Comment by p455w0rd** [comment]
is this due to a cheated-in WUT?

**Comment by Doedelsander** [comment]
Correct. Cheated in with JEI.
