### ISSUE TITLE
Massive troubles with Ultimate Terminal

### ISSUE THREAD

**Issue by JWTHDYTWA** [p455w0rd/AE2WirelessTerminalLibrary#5]
AE2 system breaks when i open ultimate WCT switched to liquid, pattern or interface mode using hotkey and deposit any item into it. System stops displaying any items, but still accepts them. Furthermore, server crashes if some item is attracted by magnet card inside Ultimate WCT switched to liquid mode.
[Crashlog](https://paste.dimdev.org/exubodopuv.mccrash)

**Comment by p455w0rd** [comment]
going to close this as it's an issue with WCT (p455w0rd/WirelessCraftingTerminal#354)
