### ISSUE TITLE
Crash with the latest wireless terminal, ae2wtlib and ae2

### ISSUE THREAD

**Issue by MadRatSRP** [p455w0rd/AE2WirelessTerminalLibrary#6]
https://paste.dimdev.org/kesawoquwo.mccrash

**Comment by p455w0rd** [comment]
can you please add me on discord (`p455w0rd#7817`) so I can send you a version to test..I'm unable to reproduce this, but it's the 2nd report I've gotten. I've implemented code that should at least stop the crash, but without being able to reproduce, I cannot verify the fix.

**Comment by p455w0rd** [comment]
I actually figured it out. It's because you're not using more than one terminal. I'll get the fix out shortly. Thanks for reporting.

**Comment by MadRatSRP** [comment]
Thank you for fixing it out. I'll try it out tomorrow and will respond if there still will be an error
